const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Spritefont2.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{Text: 0},
	{Text2: 0},
	{Text3: 0},
	{Sprite: 0},
	{Touch: 0},
	{SpriteFont: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Audio: 0},
	{Text4: 0},
	{Text5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{SCENE2PLAY: 0},
	{Sprite9: 0},
	{Text6: 0},
	{Text7: 0},
	{Sprite10: 0},
	{NAVIGSCEN2: 0},
	{Text8: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{SpriteFont2: 0},
	{lay4nav: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Text9: 0},
	{Text10: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{SpriteFont3: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Text11: 0},
	{TiledBackground2: 0},
	{Sprite25: 0},
	{Text12: 0},
	{Text13: 0},
	{Text14: 0},
	{Text15: 0},
	{Text16: 0},
	{Text17: 0},
	{SpriteFont4: 0},
	{SpriteFont5: 0},
	{Text18: 0},
	{SpriteFont6: 0},
	{Sprite26: 0},
	{Text19: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	SCENE2PLAY: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Text6: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	NAVIGSCEN2: class extends self.ISpriteInstance {},
	Text8: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	lay4nav: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Text9: class extends self.ITextInstance {},
	Text10: class extends self.ITextInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	SpriteFont3: class extends self.ISpriteFontInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Text11: class extends self.ITextInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Text12: class extends self.ITextInstance {},
	Text13: class extends self.ITextInstance {},
	Text14: class extends self.ITextInstance {},
	Text15: class extends self.ITextInstance {},
	Text16: class extends self.ITextInstance {},
	Text17: class extends self.ITextInstance {},
	SpriteFont4: class extends self.ISpriteFontInstance {},
	SpriteFont5: class extends self.ISpriteFontInstance {},
	Text18: class extends self.ITextInstance {},
	SpriteFont6: class extends self.ISpriteFontInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Text19: class extends self.ITextInstance {}
}